version: '3.8'

services:
  db:
    image: postgres:15
    container_name: whatsapp_analytics_db
    environment:
      POSTGRES_DB: whatsapp_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  waha:
    image: devlikeapro/waha-plus:latest
    container_name: whatsapp_waha
    ports:
      - "3000:3000"
    environment:
      - WAHA_WEBHOOK_URL=http://app:4000/api/webhook
      - WAHA_WEBHOOK_EVENTS=message,message.status
    volumes:
      - waha_sessions:/app/.wwebjs_auth
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    container_name: whatsapp_analytics_app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/whatsapp_analytics
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LOG_LEVEL=info
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  waha_sessions: